development:    
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ipm
  pool: 5
  username: root
  password: mysql
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ipm
  pool: 5
  username: root
  password: root
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ipm
  pool: 16
  username: root
  password: mysql
  host: localhost